-- ============================================================
-- SQL Export from Supabase for Neon Postgres
-- Generated: 2026-09-16T13:12:45.405Z
-- Total Articles: 7
-- ============================================================

-- 1. Create table structure in Neon (if not exists)
CREATE TABLE IF NOT EXISTS public.articles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text UNIQUE NOT NULL,
  title text NOT NULL,
  category text NOT NULL,
  badge text NOT NULL,
  badge_style text NOT NULL DEFAULT 'badge--gray',
  tldr text NOT NULL,
  cover_gradient text NOT NULL DEFAULT 'linear-gradient(135deg, #0B4F49 0%, #0F766E 50%, #1a8a81 100%)',
  cover_emoji text NOT NULL DEFAULT '🌙',
  card_bg text NOT NULL DEFAULT '#DFF0ED',
  sources integer NOT NULL DEFAULT 0,
  updated_at text NOT NULL,
  kesimpulan jsonb NOT NULL DEFAULT '[]'::jsonb,
  pendapat jsonb NOT NULL DEFAULT '[]'::jsonb,
  dalil jsonb NOT NULL DEFAULT '[]'::jsonb,
  sikap_praktis jsonb NOT NULL DEFAULT '[]'::jsonb,
  sumber jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- 2. Insert all articles exported from Supabase
INSERT INTO public.articles (slug, title, category, badge, badge_style, tldr, cover_gradient, cover_emoji, card_bg, sources, updated_at, kesimpulan, pendapat, dalil, sikap_praktis, sumber)
VALUES (
  'hukum-maulid-nabi',
  'Hukum Maulid Nabi ﷺ',
  'Fiqih',
  'Khilafiyah',
  'badge--gold',
  'Poin pentingnya ada di pengkhususan nya, bukan didalam maulid ada ibadahnya.',
  'linear-gradient(135deg, #0B4F49 0%, #0F766E 50%, #1a8a81 100%)',
  '🌙',
  '#DFF0ED',
  5,
  'Jan 2025',
  '["Menurut rujukan Rumaysho dan Konsultasi Syariah, perayaan Maulid Nabi ﷺ sebagai ritual ibadah tahunan tidak dibolehkan.","Alasannya: Nabi ﷺ, para sahabat, tabi''in, tabi''ut tabi''in, dan imam empat mazhab tidak dikenal merayakannya.","Mereka menilai Maulid sebagai amalan yang diada-adakan dalam agama, karena mengkhususkan waktu dan bentuk ibadah yang tidak dicontohkan.","Yang disyariatkan adalah mencintai Nabi ﷺ setiap waktu dengan ittiba'', shalawat, belajar sirah, dan mengamalkan sunnah beliau."]'::jsonb,
  '[{"bar":"haram","view":"Menilai sebagai bid''ah dalam agama","detail":"Rumaysho dan Konsultasi Syariah berpandangan bahwa perayaan Maulid Nabi ﷺ tidak memiliki dasar dari Nabi ﷺ dan para sahabat. Karena itu, menjadikannya sebagai ritual ibadah tahunan dinilai sebagai amalan yang tidak disyariatkan.","school":"Pendapat 1 — Tidak Membolehkan Maulid"},{"bar":"khilaf","view":"Shalawat, sirah, dan sedekah tetap dianjurkan","detail":"Shalawat kepada Nabi ﷺ, belajar sirah, dan sedekah adalah amalan yang baik. Namun masalahnya ada pada pengkhususan tanggal tertentu, seperti 12 Rabiul Awal, sebagai perayaan ibadah tahunan.","school":"Pendapat 2 — Ibadahnya Baik, Pengkhususannya Bermasalah"},{"bar":"halal","view":"Mencintai Nabi ﷺ bukan hanya dengan acara tahunan","detail":"Cinta kepada Nabi ﷺ ditunjukkan dengan mengikuti sunnah beliau, menaati ajarannya, memperbanyak shalawat, mempelajari sirah, dan menghidupkan sunnah dalam kehidupan sehari-hari.","school":"Pendapat 3 — Cinta Nabi Harus dengan Ittiba''"}]'::jsonb,
  '[{"label":"Hadits — Bukhari & Muslim","arabic":"مَنْ أَحْدَثَ فِي أَمْرِنَا هَذَا مَا لَيْسَ مِنْهُ فَهُوَ رَدٌّ","source":"HR. Bukhari dan Muslim · Status: Shahih","terjemahan":"\"Barangsiapa mengada-adakan dalam urusan agama kami ini sesuatu yang bukan darinya, maka amalan itu tertolak.\""},{"label":"Al-Qur''an — QS. Al-Ahzab: 56","arabic":"إِنَّ اللَّهَ وَمَلَائِكَتَهُ يُصَلُّونَ عَلَى النَّبِيِّ ۚ يَا أَيُّهَا الَّذِينَ آمَنُوا صَلُّوا عَلَيْهِ وَسَلِّمُوا تَسْلِيمًا","source":"QS. Al-Ahzab [33]: 56","terjemahan":"\"Sesungguhnya Allah dan para malaikat-Nya bershalawat untuk Nabi. Wahai orang-orang yang beriman, bershalawatlah kalian untuk Nabi dan ucapkanlah salam dengan penuh penghormatan kepadanya.\""}]'::jsonb,
  '["Tidak menjadikan Maulid Nabi ﷺ sebagai ritual ibadah tahunan, jika mengikuti pendapat Rumaysho dan Konsultasi Syariah.","Tetap memperbanyak shalawat kepada Nabi ﷺ kapan saja, tanpa harus menunggu bulan atau tanggal tertentu.","Mempelajari sirah Nabi ﷺ secara rutin agar cinta kepada beliau semakin kuat dan benar.","Menghidupkan sunnah Nabi ﷺ dalam akidah, ibadah, akhlak, keluarga, dan muamalah sehari-hari.","Tidak mencela orang secara berlebihan, tetapi tetap menjelaskan pendapat dengan ilmu dan adab."]'::jsonb,
  '[{"title":"Sejarah Kelam Maulid Nabi — Bagian 2","author":"Rumaysho · Tidak membolehkan Maulid sebagai perayaan ibadah tahunan"},{"title":"Meskipun Kelam, Maulid Nabi Tetap Ada Pembelaan","author":"Rumaysho · Membahas asal-usul dan pembelaan terhadap Maulid"},{"title":"Pembahasan Maulid Nabi","author":"Konsultasi Syariah · Menilai pengkhususan Maulid sebagai amalan yang tidak dicontohkan"},{"title":"Hadits \"Barangsiapa mengada-adakan dalam urusan agama kami…\"","author":"HR. Bukhari dan Muslim · Dalil umum tentang larangan bid''ah dalam agama"},{"title":"QS. Al-Ahzab [33]: 56","author":"Dalil tentang perintah bershalawat kepada Nabi ﷺ"}]'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  badge = EXCLUDED.badge,
  badge_style = EXCLUDED.badge_style,
  tldr = EXCLUDED.tldr,
  cover_gradient = EXCLUDED.cover_gradient,
  cover_emoji = EXCLUDED.cover_emoji,
  card_bg = EXCLUDED.card_bg,
  sources = EXCLUDED.sources,
  updated_at = EXCLUDED.updated_at,
  kesimpulan = EXCLUDED.kesimpulan,
  pendapat = EXCLUDED.pendapat,
  dalil = EXCLUDED.dalil,
  sikap_praktis = EXCLUDED.sikap_praktis,
  sumber = EXCLUDED.sumber;

INSERT INTO public.articles (slug, title, category, badge, badge_style, tldr, cover_gradient, cover_emoji, card_bg, sources, updated_at, kesimpulan, pendapat, dalil, sikap_praktis, sumber)
VALUES (
  'apakah-qunut-nazilah-ada-dalilnya',
  'Apakah Qunut Nazilah ada dalilnya?',
  'Fiqih',
  'Khilafiyah',
  'badge--gold',
  'Qunut Nazilah disyariatkan saat musibah besar menimpa kaum muslimin, bukan ritual rutin tanpa sebab.',
  'linear-gradient(135deg, #0B4F49 0%, #0F766E 50%, #1a8a81 100%)',
  '🌙',
  '#EDE9FE',
  4,
  'Jun 2026',
  '["Qunut Nazilah ada dalil shahih dari Nabi ﷺ.","Dilakukan saat ada musibah besar yang menimpa kaum muslimin.","Tidak dilakukan terus-menerus tanpa sebab.","Bukan bid‘ah karena pernah dicontohkan Rasulullah ﷺ."]'::jsonb,
  '[{"bar":"halal","view":"Disyariatkan ketika ada nazilah atau musibah besar.","detail":"Nabi ﷺ pernah melakukan qunut selama sebulan karena terbunuhnya para sahabat di Bi’r Ma‘unah. Ini menunjukkan Qunut Nazilah boleh dilakukan ketika ada musibah besar, peperangan, penindasan, atau bencana yang menimpa kaum muslimin.","school":"Pendapat Sunnah"},{"bar":"khilaf","view":"Ada perbedaan tentang shalat apa saja yang dibacakan Qunut Nazilah.","detail":"Sebagian ulama membolehkan Qunut Nazilah pada semua shalat wajib, sebagian lainnya membatasi pada shalat tertentu. Namun inti kesepakatannya: Qunut Nazilah bukan ritual harian biasa, tetapi terkait sebab musibah.","school":"Perbedaan Praktik Ulama"}]'::jsonb,
  '[{"label":"Hadits — Bukhari dan Muslim","arabic":"قَنَتَ النَّبِيُّ ﷺ شَهْرًا يَدْعُو عَلَى رِعْلٍ وَذَكْوَانَ","source":"HR. Bukhari dan Muslim, dari Anas bin Malik radhiyallahu ‘anhu","terjemahan":"Nabi ﷺ melakukan qunut selama satu bulan, mendoakan keburukan atas kabilah Ri‘l dan Dzakwan."},{"label":"Hadits — Muslim","arabic":"إِنَّمَا جُعِلَ الْإِمَامُ لِيُؤْتَمَّ بِهِ","source":"HR. Muslim no. 411","terjemahan":"Sesungguhnya imam itu dijadikan untuk diikuti."}]'::jsonb,
  '["Ikuti imam jika ia membaca Qunut Nazilah dalam shalat berjamaah.","Jangan menganggap Qunut Nazilah sebagai ritual rutin tanpa sebab.","Lakukan ketika ada musibah besar yang nyata menimpa kaum muslimin.","Doanya boleh berisi permohonan pertolongan untuk kaum muslimin dan doa kebinasaan bagi pihak zalim.","Tidak perlu menyamakan Qunut Nazilah dengan amalan baru seperti maulid, karena Qunut Nazilah punya dalil shahih."]'::jsonb,
  '[{"title":"Mengkaji Qunut Nazilah","author":"Muslim.or.id"},{"title":"Qunut Nazilah Ketika Musibah","author":"Rumaysho.com"},{"title":"Shahih Bukhari","author":"Imam Al-Bukhari"},{"title":"Shahih Muslim","author":"Imam Muslim"}]'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  badge = EXCLUDED.badge,
  badge_style = EXCLUDED.badge_style,
  tldr = EXCLUDED.tldr,
  cover_gradient = EXCLUDED.cover_gradient,
  cover_emoji = EXCLUDED.cover_emoji,
  card_bg = EXCLUDED.card_bg,
  sources = EXCLUDED.sources,
  updated_at = EXCLUDED.updated_at,
  kesimpulan = EXCLUDED.kesimpulan,
  pendapat = EXCLUDED.pendapat,
  dalil = EXCLUDED.dalil,
  sikap_praktis = EXCLUDED.sikap_praktis,
  sumber = EXCLUDED.sumber;

INSERT INTO public.articles (slug, title, category, badge, badge_style, tldr, cover_gradient, cover_emoji, card_bg, sources, updated_at, kesimpulan, pendapat, dalil, sikap_praktis, sumber)
VALUES (
  'baca-al-ikhlas-1000-kali-di-tahun-baru-islam',
  'Baca Al ikhlas 1000 kali di Tahun Baru Islam',
  'Fiqih',
  'Kontroversial',
  'badge--gold',
  'Tidak ditemukan hadits shahih yang mengkhususkan membaca surat tertentu 1000 kali pada awal Muharram.',
  'linear-gradient(135deg, #0B4F49 0%, #0F766E 50%, #1a8a81 100%)',
  '🌙',
  '#DFF0ED',
  3,
  'Jun 2026',
  '["Tidak ada hadits shahih yang memerintahkan membaca Al-Ikhlas, Yasin, atau surat tertentu 1000 kali pada awal Muharram.","Membaca Al-Qur''an adalah ibadah yang disyariatkan, tetapi pengkhususan jumlah dan waktu memerlukan dalil.","Rumaysho menegaskan bahwa penetapan jumlah bacaan dan waktu tertentu harus memiliki landasan syariat.","Amalan membaca surat 1000 kali pada tahun baru Hijriah tidak ditemukan tuntunannya dari Nabi ﷺ maupun para sahabat."]'::jsonb,
  '[{"bar":"haram","view":"Tidak disyariatkan mengkhususkan bacaan 1000 kali pada awal tahun.","detail":"Mereka menegaskan bahwa ibadah yang dikaitkan dengan jumlah, waktu, atau tata cara tertentu memerlukan dalil. Tidak ditemukan riwayat shahih yang mengkhususkan bacaan surat tertentu 1000 kali pada awal Muharram.","school":"Pendapat Rumaysho & Konsultasi Syariah"},{"bar":"khilaf","view":"Diamalkan sebagai tradisi atau amalan turun-temurun.","detail":"Sebagian kaum muslimin mengamalkan bacaan tertentu 1000 kali pada awal tahun berdasarkan anjuran ulama atau tradisi lokal. Namun praktik ini tidak memiliki dasar hadits shahih yang dikenal dalam pembahasan Rumaysho maupun Konsultasi Syariah.","school":"Sebagian Praktik Masyarakat"}]'::jsonb,
  '[{"label":"Al-Qur''an — QS. Al-Baqarah: 185","arabic":"يُرِيدُ اللَّهُ بِكُمُ الْيُسْرَ وَلَا يُرِيدُ بِكُمُ الْعُسْرَ","source":"QS. Al-Baqarah: 185","terjemahan":"Allah menghendaki kemudahan bagimu dan tidak menghendaki kesulitan bagimu."},{"label":"Hadits — Bukhari dan Muslim","arabic":"مَنْ أَحْدَثَ فِي أَمْرِنَا هَذَا مَا لَيْسَ مِنْهُ فَهُوَ رَدٌّ","source":"HR. Bukhari dan Muslim","terjemahan":"Barang siapa mengada-adakan dalam urusan agama kami sesuatu yang bukan darinya, maka amalan itu tertolak."}]'::jsonb,
  '["Perbanyak membaca Al-Qur''an tanpa mengikat diri pada jumlah yang tidak memiliki dalil.","Jika ingin membaca Al-Ikhlas, cukup amalkan keutamaan yang memiliki hadits shahih seperti 10 kali.","Hindari menyebarkan amalan yang tidak diketahui sumber haditsnya.","Fokus pada amalan yang jelas tuntunannya dari Nabi ﷺ.","Jika mendengar klaim keutamaan tertentu, periksa sumber dan derajat haditsnya terlebih dahulu."]'::jsonb,
  '[{"title":"Doa Awal dan Akhir Tahun Hijriyah, Adakah Tuntunan?","author":"Rumaysho.com"},{"title":"Ayat 1000 Dinar, Ayat Pesugihan Biar Cepat Kaya?","author":"Rumaysho.com"},{"title":"Amalkan Surat Al-Ikhlas Bersama Surat Lainnya di Enam Waktu Ini","author":"Rumaysho.com"}]'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  badge = EXCLUDED.badge,
  badge_style = EXCLUDED.badge_style,
  tldr = EXCLUDED.tldr,
  cover_gradient = EXCLUDED.cover_gradient,
  cover_emoji = EXCLUDED.cover_emoji,
  card_bg = EXCLUDED.card_bg,
  sources = EXCLUDED.sources,
  updated_at = EXCLUDED.updated_at,
  kesimpulan = EXCLUDED.kesimpulan,
  pendapat = EXCLUDED.pendapat,
  dalil = EXCLUDED.dalil,
  sikap_praktis = EXCLUDED.sikap_praktis,
  sumber = EXCLUDED.sumber;

INSERT INTO public.articles (slug, title, category, badge, badge_style, tldr, cover_gradient, cover_emoji, card_bg, sources, updated_at, kesimpulan, pendapat, dalil, sikap_praktis, sumber)
VALUES (
  'kalo-tadarus-quran-habis-magrib',
  'Kalo tadarus Quran habis Magrib?',
  'Fiqih',
  'Mubah',
  'badge--gold',
  'Membaca Al-Qur''an setelah Maghrib secara rutin boleh dan baik selama tidak diyakini sebagai ibadah dengan keutamaan khusus yang tidak berdalil.',
  'linear-gradient(135deg, #0B4F49 0%, #0F766E 50%, #1a8a81 100%)',
  '🌙',
  '#DBEAFE',
  3,
  'Jun 2026',
  '["Membaca Al-Qur''an setelah Maghrib termasuk amalan yang baik dan disyariatkan secara umum.","Menentukan waktu setelah Maghrib untuk menjaga konsistensi ibadah diperbolehkan.","Tidak ada hadits shahih yang mengkhususkan membaca Al-Qur''an setelah Maghrib dengan keutamaan tertentu.","Yang tidak dibolehkan adalah meyakini adanya keutamaan khusus tanpa dalil."]'::jsonb,
  '[{"bar":"halal","view":"Boleh dan dianjurkan sebagai bentuk menjaga rutinitas ibadah.","detail":"Membaca Al-Qur''an adalah ibadah yang disyariatkan setiap waktu. Menentukan jadwal setelah Maghrib untuk memudahkan istiqamah termasuk pengaturan pribadi dan bukan pengkhususan syariat.","school":"Pendapat Rumaysho & Konsultasi Syariah"},{"bar":"khilaf","view":"Menjadi bermasalah jika diyakini memiliki keutamaan khusus tanpa dalil.","detail":"Jika seseorang meyakini bahwa membaca Al-Qur''an setelah Maghrib memiliki keutamaan tertentu yang tidak disebutkan dalam dalil shahih, maka keyakinan tersebut perlu ditinggalkan.","school":"Batasan Pengkhususan Waktu"}]'::jsonb,
  '[{"label":"Al-Qur''an — QS. Al-Muzzammil: 20","arabic":"فَاقْرَءُوا مَا تَيَسَّرَ مِنَ الْقُرْآنِ","source":"QS. Al-Muzzammil: 20","terjemahan":"Maka bacalah apa yang mudah bagimu dari Al-Qur''an."},{"label":"Hadits — Bukhari dan Muslim","arabic":"خَيْرُ الْأَعْمَالِ أَدْوَمُهَا وَإِنْ قَلَّ","source":"HR. Bukhari no. 6464 dan Muslim no. 783","terjemahan":"Amalan yang paling dicintai Allah adalah yang paling rutin walaupun sedikit."}]'::jsonb,
  '["Tetapkan target harian membaca Al-Qur''an yang realistis setelah Maghrib.","Jangan meyakini adanya keutamaan khusus waktu Maghrib kecuali ada dalil yang shahih.","Fokus pada istiqamah dan tadabbur daripada jumlah bacaan semata.","Boleh membuat jadwal tetap untuk membantu menjaga kebiasaan membaca Al-Qur''an.","Jika suatu hari terlewat, lanjutkan kembali tanpa merasa harus mengganti dengan ritual tertentu."]'::jsonb,
  '[{"title":"Amalan yang Paling Dicintai Allah adalah yang Rutin","author":"Rumaysho.com"},{"title":"Membaca Al-Qur''an dan Keutamaannya","author":"Rumaysho.com"},{"title":"Fatwa Seputar Rutinitas Ibadah Harian","author":"KonsultasiSyariah.com"}]'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  badge = EXCLUDED.badge,
  badge_style = EXCLUDED.badge_style,
  tldr = EXCLUDED.tldr,
  cover_gradient = EXCLUDED.cover_gradient,
  cover_emoji = EXCLUDED.cover_emoji,
  card_bg = EXCLUDED.card_bg,
  sources = EXCLUDED.sources,
  updated_at = EXCLUDED.updated_at,
  kesimpulan = EXCLUDED.kesimpulan,
  pendapat = EXCLUDED.pendapat,
  dalil = EXCLUDED.dalil,
  sikap_praktis = EXCLUDED.sikap_praktis,
  sumber = EXCLUDED.sumber;

INSERT INTO public.articles (slug, title, category, badge, badge_style, tldr, cover_gradient, cover_emoji, card_bg, sources, updated_at, kesimpulan, pendapat, dalil, sikap_praktis, sumber)
VALUES (
  'shalawat-shahih-dari-nabi',
  'Shalawat Shahih dari Nabi ﷺ',
  'Adab',
  'Sunnah',
  'badge--blue',
  'Shalawat terbaik adalah lafaz yang diajarkan langsung oleh Nabi ﷺ dalam hadits shahih.',
  'linear-gradient(135deg, #92400e 0%, #d97706 60%, #fbbf24 100%)',
  '☀️',
  '#FEF3C7',
  4,
  'Jun 2026',
  '["Shalawat yang paling aman dan utama adalah yang ma''tsur dari Nabi ﷺ.","Shalawat Ibrahimiyah memiliki beberapa variasi lafaz shahih.","Riwayat Ka''b bin Ujrah, Abu Humaid, dan Abu Mas''ud semuanya shahih.","Shalawat populer seperti Nariyah, Fatih, Munjiyat, dan Tibbil Qulub bukan lafaz hadits Nabi ﷺ."]'::jsonb,
  '[{"bar":"halal","view":"Utamakan shalawat yang shahih dan ma''tsur.","detail":"Lafaz shalawat yang diajarkan langsung oleh Nabi ﷺ lebih utama dan lebih selamat untuk diamalkan, terutama dalam shalat dan dzikir harian.","school":"Pendapat Rumaysho & Konsultasi Syariah"},{"bar":"khilaf","view":"Tidak otomatis haram, tetapi bukan hadits Nabi ﷺ.","detail":"Shalawat seperti Nariyah, Fatih, Munjiyat, dan Tibbil Qulub adalah susunan ulama atau tradisi belakangan. Tidak boleh diyakini sebagai lafaz sunnah khusus atau memiliki keutamaan tertentu kecuali ada dalil shahih.","school":"Shalawat Populer Susunan Ulama"}]'::jsonb,
  '[{"label":"Hadits — Bukhari dan Muslim","arabic":"اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ، اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ","source":"HR. Bukhari dan Muslim, dari Ka''b bin Ujrah radhiyallahu ‘anhu","terjemahan":"Ya Allah, limpahkanlah shalawat kepada Muhammad dan keluarga Muhammad sebagaimana Engkau melimpahkan shalawat kepada Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia. Ya Allah, berkahilah Muhammad dan keluarga Muhammad sebagaimana Engkau memberkahi Ibrahim dan keluarga Ibrahim. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia."},{"label":"Hadits — Muslim","arabic":"اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى آلِ إِبْرَاهِيمَ، وَبَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَى آلِ إِبْرَاهِيمَ فِي الْعَالَمِينَ إِنَّكَ حَمِيدٌ مَجِيدٌ","source":"HR. Muslim no. 405, dari Abu Mas''ud Al-Anshari radhiyallahu ‘anhu","terjemahan":"Ya Allah, limpahkanlah shalawat kepada Muhammad dan keluarga Muhammad sebagaimana Engkau melimpahkan shalawat kepada keluarga Ibrahim. Dan berkahilah Muhammad dan keluarga Muhammad sebagaimana Engkau memberkahi keluarga Ibrahim di seluruh alam. Sesungguhnya Engkau Maha Terpuji lagi Maha Mulia."}]'::jsonb,
  '["Utamakan shalawat Ibrahimiyah dan variasi lafaz shahih dari Nabi ﷺ.","Boleh bershalawat dengan lafaz ringkas seperti Allahumma shalli ‘ala Muhammad.","Jangan meyakini shalawat populer memiliki keutamaan khusus tanpa dalil shahih.","Dalam tasyahud, gunakan lafaz shalawat yang shahih dari hadits.","Tidak perlu mencari-cari lafaz shalawat buatan jika yang ma''tsur sudah mencukupi."]'::jsonb,
  '[{"title":"Sifat Shalat Nabi: Bacaan Shalawat dalam Tasyahud","author":"Rumaysho.com"},{"title":"Shalawat yang Diajarkan Nabi ﷺ","author":"KonsultasiSyariah.com"},{"title":"Shahih Bukhari","author":"Imam Al-Bukhari"},{"title":"Shahih Muslim","author":"Imam Muslim"}]'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  badge = EXCLUDED.badge,
  badge_style = EXCLUDED.badge_style,
  tldr = EXCLUDED.tldr,
  cover_gradient = EXCLUDED.cover_gradient,
  cover_emoji = EXCLUDED.cover_emoji,
  card_bg = EXCLUDED.card_bg,
  sources = EXCLUDED.sources,
  updated_at = EXCLUDED.updated_at,
  kesimpulan = EXCLUDED.kesimpulan,
  pendapat = EXCLUDED.pendapat,
  dalil = EXCLUDED.dalil,
  sikap_praktis = EXCLUDED.sikap_praktis,
  sumber = EXCLUDED.sumber;

INSERT INTO public.articles (slug, title, category, badge, badge_style, tldr, cover_gradient, cover_emoji, card_bg, sources, updated_at, kesimpulan, pendapat, dalil, sikap_praktis, sumber)
VALUES (
  'puasa-asyura-dan-tasua',
  'Puasa Asyura dan Tasu''a',
  'Puasa',
  'Sunnah',
  'badge--blue',
  'Puasa Asyura pada 10 Muharram adalah sunnah yang dapat menghapus dosa-dosa kecil setahun yang lalu.',
  'linear-gradient(135deg, #92400e 0%, #d97706 60%, #fbbf24 100%)',
  '☀️',
  '#FEF3C7',
  3,
  'Jun 2026',
  '["Puasa Asyura dilakukan pada tanggal 10 Muharram dan hukumnya sunnah.","Keutamaan puasa Asyura adalah menghapus dosa-dosa kecil setahun sebelumnya.","Lebih utama menggabungkan puasa tanggal 9 dan 10 Muharram untuk menyelisihi Yahudi.","Minimal tetap mendapatkan keutamaan dengan berpuasa tanggal 10 Muharram saja."]'::jsonb,
  '[{"bar":"halal","view":"Puasa Asyura sangat dianjurkan (sunnah muakkadah).","detail":"Berdasarkan hadits shahih, Nabi ﷺ menganjurkan puasa Asyura dan menjelaskan keutamaannya sebagai penghapus dosa setahun yang lalu.","school":"Pendapat Mayoritas Ulama"},{"bar":"halal","view":"Yang paling utama adalah puasa 9 dan 10 Muharram.","detail":"Para ulama menjelaskan bahwa tingkatan terbaik adalah puasa 9 dan 10 Muharram, atau ditambah 11 Muharram. Tujuannya untuk menyelisihi praktik Yahudi yang hanya berpuasa pada tanggal 10.","school":"Tingkatan Pelaksanaan"}]'::jsonb,
  '[{"label":"Hadits — Shahih Muslim","arabic":"وَصِيَامُ يَوْمِ عَاشُورَاءَ أَحْتَسِبُ عَلَى اللَّهِ أَنْ يُكَفِّرَ السَّنَةَ الَّتِي قَبْلَهُ","source":"HR. Muslim no. 1162","terjemahan":"Puasa hari Asyura, aku berharap kepada Allah agar menghapus dosa setahun sebelumnya."},{"label":"Hadits — Shahih Muslim","arabic":"لَئِنْ بَقِيتُ إِلَى قَابِلٍ لَأَصُومَنَّ التَّاسِعَ","source":"HR. Muslim no. 1134","terjemahan":"Jika aku masih hidup sampai tahun depan, sungguh aku akan berpuasa pada hari kesembilan."}]'::jsonb,
  '["Usahakan berpuasa pada tanggal 9 dan 10 Muharram.","Jika tidak mampu, tetap berpuasa pada tanggal 10 Muharram.","Niatkan puasa untuk mengharap pahala dan ampunan dari Allah.","Jangan menganggap puasa Asyura sebagai kewajiban karena hukumnya sunnah.","Perhatikan penetapan awal Muharram berdasarkan kalender Hijriah yang berlaku di daerah setempat."]'::jsonb,
  '[{"title":"Puasa Tasu''a dan Asyura","author":"Rumaysho.com"},{"title":"Panduan Puasa Muharram","author":"Rumaysho.com"},{"title":"Shahih Muslim","author":"Imam Muslim"}]'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  badge = EXCLUDED.badge,
  badge_style = EXCLUDED.badge_style,
  tldr = EXCLUDED.tldr,
  cover_gradient = EXCLUDED.cover_gradient,
  cover_emoji = EXCLUDED.cover_emoji,
  card_bg = EXCLUDED.card_bg,
  sources = EXCLUDED.sources,
  updated_at = EXCLUDED.updated_at,
  kesimpulan = EXCLUDED.kesimpulan,
  pendapat = EXCLUDED.pendapat,
  dalil = EXCLUDED.dalil,
  sikap_praktis = EXCLUDED.sikap_praktis,
  sumber = EXCLUDED.sumber;

INSERT INTO public.articles (slug, title, category, badge, badge_style, tldr, cover_gradient, cover_emoji, card_bg, sources, updated_at, kesimpulan, pendapat, dalil, sikap_praktis, sumber)
VALUES (
  'mengusap-wajah-setelah-berdoa',
  'Mengusap Wajah Setelah Berdoa',
  'Adab',
  'Khilafiyah',
  'badge--gold',
  'Mengusap wajah setelah berdoa adalah masalah khilafiyah. Pendapat yang dipilih Rumaysho adalah tidak disunnahkan karena hadits-haditsnya dinilai lemah.',
  'linear-gradient(135deg, #0B4F49 0%, #0F766E 50%, #1a8a81 100%)',
  '🌙',
  '#DFF0ED',
  3,
  'Jun 2026',
  '["Mengusap wajah setelah berdoa merupakan masalah khilafiyah di kalangan ulama.","Rumaysho memilih pendapat bahwa amalan tersebut tidak disunnahkan.","Hadits-hadits tentang mengusap wajah setelah berdoa dinilai lemah oleh banyak ulama.","Tidak mengusap wajah setelah berdoa tetap sesuai dengan sunnah Nabi ﷺ menurut pendapat yang dipilih Rumaysho."]'::jsonb,
  '[{"bar":"haram","view":"Tidak disunnahkan mengusap wajah setelah berdoa.","detail":"Riwayat-riwayat yang menjelaskan Nabi ﷺ mengusap wajah setelah berdoa dinilai dhaif sehingga tidak cukup kuat dijadikan dasar untuk menjadikan amalan ini sebagai sunnah yang rutin dilakukan.","school":"Pendapat Rumaysho, Al-Lajnah Ad-Da''imah, Syaikh Ibnu Utsaimin"},{"bar":"khilaf","view":"Dibolehkan karena riwayat-riwayatnya saling menguatkan.","detail":"Sebagian ulama seperti Ibnu Hajar Al-''Asqalani berpendapat bahwa banyaknya jalur riwayat dapat mengangkat derajat hadits menjadi hasan li ghairihi, sehingga mengusap wajah setelah berdoa diperbolehkan.","school":"Pendapat Sebagian Ulama"}]'::jsonb,
  '[{"label":"Hadits — Abu Dawud","arabic":"إِذَا دَعَا أَحَدُكُمْ فَلَا يَرُدَّ يَدَيْهِ حَتَّى يَمْسَحَ بِهِمَا وَجْهَهُ","source":"HR. Abu Dawud no. 1492 (diperselisihkan; dinilai dhaif oleh banyak ulama)","terjemahan":"Apabila salah seorang di antara kalian berdoa, janganlah ia menurunkan kedua tangannya hingga mengusap wajahnya dengan kedua tangan tersebut."},{"label":"Kaidah Sunnah","arabic":"خَيْرُ الْهَدْيِ هَدْيُ مُحَمَّدٍ ﷺ","source":"Makna hadits shahih dalam Shahih Muslim","terjemahan":"Sebaik-baik petunjuk adalah petunjuk Muhammad ﷺ."}]'::jsonb,
  '["Berdoalah dengan penuh kekhusyukan dan ikhlas kepada Allah.","Jika tidak mengusap wajah setelah berdoa, tidak mengapa dan itulah pendapat yang dipilih Rumaysho.","Jangan menganggap mengusap wajah sebagai bagian yang harus ada dalam setiap doa.","Hormati perbedaan pendapat ulama dalam masalah ini dan hindari saling menyalahkan.","Utamakan mengikuti amalan yang memiliki dalil paling kuat menurut kemampuan ilmu yang dimiliki."]'::jsonb,
  '[{"title":"Hukum Mengusap Wajah Setelah Salam","author":"Rumaysho.com"},{"title":"Fatwa Al-Lajnah Ad-Da''imah tentang Mengusap Wajah Setelah Doa","author":"Al-Lajnah Ad-Da''imah"},{"title":"Fatawa Nur ''ala Ad-Darb","author":"Syaikh Muhammad bin Shalih Al-Utsaimin"}]'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  badge = EXCLUDED.badge,
  badge_style = EXCLUDED.badge_style,
  tldr = EXCLUDED.tldr,
  cover_gradient = EXCLUDED.cover_gradient,
  cover_emoji = EXCLUDED.cover_emoji,
  card_bg = EXCLUDED.card_bg,
  sources = EXCLUDED.sources,
  updated_at = EXCLUDED.updated_at,
  kesimpulan = EXCLUDED.kesimpulan,
  pendapat = EXCLUDED.pendapat,
  dalil = EXCLUDED.dalil,
  sikap_praktis = EXCLUDED.sikap_praktis,
  sumber = EXCLUDED.sumber;

